# SPDX-License-Identifier: Apache-2.0

# GitHub Dependabot configuration file
version: 2
updates:
  # Maintain dependencies for GitHub Actions
  - package-ecosystem: "github-actions"
    directories:
    - "/"
    - ".github/actions/cldk-setup"
    schedule:
      interval: "daily"
