#!/bin/sh
#
# See prepare-commit-message.sample for an example hook script
# with other actions you could take.
#
# Checks that the Signed-off-by line is in the message and fails
# if not. The ".sample" shows how to _add_ the line, if desired.

COMMIT_MSG_FILE=$1
COMMIT_SOURCE=$2
SHA1=$3

/usr/bin/perl -i.bak -ne 'print unless(m/^. Please enter the commit message/..m/^#$/)' "$COMMIT_MSG_FILE"

grep -q 'Signed-off-by: ' $COMMIT_MSG_FILE
if [[ $? -ne 0 ]]
then
  cat <<\EOF
Error: Commits must be signed off. For example, add "-s" to your commit command:
  git commit -s -m "comment" ...

For more information, see:
https://github.com/The-AI-Alliance/community/blob/main/CONTRIBUTING.md#legal
EOF
	exit 1
fi

