name: 'Additional Test Setup'
description: 'Additional Test Setup for CLDK'
runs:
  using: "composite"
  steps:
    - name: Setup Java
      uses: actions/setup-java@dded0888837ed1f317902acf8a20df0ad188d165 # v5.0.0
      with:
        distribution: 'temurin'
        java-version: '11'

    - name: Install Ollama and start server
      shell: bash
      run: |
        curl -fsSL https://ollama.com/install.sh | sudo -E sh

    - name: Wait for Ollama server
      shell: bash
      run: |
        sleep 10
        time curl -i http://localhost:11434

    - name: Pull Granite model
      shell: bash
      run: |
        ollama pull granite-code:3b

