name: CI for CLDK Notebooks

on:
  push:
    branches:
      - main
    paths:
      - 'recipes/CodeLLM_DevKit/code_summarization.ipynb'
      - 'recipes/CodeLLM_DevKit/generate_unit_tests.ipynb'
      - 'recipes/CodeLLM_DevKit/validating_code_translation.ipynb'
  pull_request:
    branches:
      - main
    paths:
      - 'recipes/CodeLLM_DevKit/code_summarization.ipynb'
      - 'recipes/CodeLLM_DevKit/generate_unit_tests.ipynb'
      - 'recipes/CodeLLM_DevKit/validating_code_translation.ipynb'

jobs:
  test-java-notebooks:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Set up Java
        run: |
          sudo apt-get update    
          sudo apt-get install -y default-jdk    
          java -version    
          echo "JAVA_HOME=$(readlink -f /usr/bin/java | sed "s:bin/java::")" >> $GITHUB_ENV    

      - name: Verify Java installation
        run: |
          echo $JAVA_HOME    
          java -version    

      - name: Setup Ollama
        run : |
          curl https://ollama.ai/install.sh | sh  
          nohup ollama serve > ollama_serve.log 2>&1 &    
          sleep 10  
          ollama pull granite-code:3b 

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip    
          pip install nbconvert nbclient ipykernel
          

      - name: Run Java Notebooks
        run: |
          notebooks=$(cat .github/notebook_lists/cldk_notebooks.txt | tr '\n' ' ')  
          for notebook in $notebooks; do  
            echo "Executing $notebook"  
            jupyter nbconvert --to notebook --execute --inplace $notebook  
          done  
  
